Remove undefined methods/variables from signature
The constructors signature implies that there is no need to pass
additional arguments besied `original_array`.

However, the snippet below results in an error

```
RestfulResource::PaginatedArray.new([])
=> NameError: undefined local variable or method `previous_page_url' for []:RestfulResource::PaginatedArray
```

Assuming that we allow urls to be `nil`
https://github.com/carwow/restful_resource/blob/master/lib/restful_resource/paginated_array.rb#L20
we can default to optional params with `nil` default values